### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by AsaAyers** [skandasoft/navigate#1]
Since I write a mix of CoffeeScript and Javascript I like to leave the extensions off of my `require()`s. IDK if it's a good idea, but it's what I've been doing ¯\_(ツ)_/¯

   var BaseStore = require('./base.js'); // Jumps correctly
   var BaseStore = require('./base'); // produces an exception

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.0.6
### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:112

TypeError: Arguments to path.resolve must be strings
  at Object.win32.resolve (path.js:112:13)
  at setopts (C:\Users\Asa\.atom\packages\navigate\node_modules\glob\common.js:83:28)
  at new Glob (C:\Users\Asa\.atom\packages\navigate\node_modules\glob\glob.js:115:3)
  at glob (C:\Users\Asa\.atom\packages\navigate\node_modules\glob\glob.js:72:10)
  at globSearch (C:\Users\Asa\.atom\packages\navigate\lib\navigate.coffee:68:21)
  at C:\Users\Asa\.atom\packages\navigate\lib\navigate.coffee:89:19
  at FSReqWrap.cb [as oncomplete] (fs.js:229:19)

```
### Commands

```
     -0:30.2 settings-view:open (atom-text-editor.editor.vim-mode.visual-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-lines"
    ],
    "projectHome": "C:\\Users\\Asa\\Documents\\GitHub"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
ex-mode, v0.3.0
gist-it, v0.6.4
highlight-line, v0.9.3
highlight-selected, v0.9.0
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-eslint, v0.4.1
minimap, v4.3.1
minimap-find-and-replace, v4.0.0
minimap-git-diff, v4.0.0
minimap-highlight-selected, v4.1.0
navigate, v0.0.6
react, v0.9.10
toggle-quotes, v0.10.0
tree-view-open-files, v0.2.3
vim-mode, v0.33.0
vim-surround, v0.4.2

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Fixed. Please check the latest patch.

**Comment by AsaAyers** [comment]
The exception is gone now.
