### ISSUE TITLE
Uncaught TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by vuonghuuphuc** [skandasoft/navigate#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.1.7
### Stack Trace

Uncaught TypeError: Cannot read property 'append' of undefined

```
At C:\Users\PC4\.atom\packages\navigate\lib\navigate-view.coffee:28

TypeError: Cannot read property 'append' of undefined
    at ListView.initialize (C:\Users\PC4\.atom\packages\navigate\lib\navigate-view.coffee:46:25)
    at ListView.View (C:\Users\PC4\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at ListView.SelectListView (C:\Users\PC4\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:18:51)
    at new ListView (C:\Users\PC4\.atom\packages\navigate\lib\navigate-view.coffee:38:45)
    at Object.module.exports.matchFile (C:\Users\PC4\.atom\packages\navigate\lib\navigate.coffee:292:22)
    at C:\Users\PC4\.atom\packages\navigate\lib\navigate.coffee:184:30
    at f (C:\Users\PC4\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\once\once.js:17:25)
    at Glob.<anonymous> (C:\Users\PC4\.atom\packages\navigate\node_modules\glob\glob.js:130:7)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:166:7)
```
### Commands

```
     -0:37.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:13.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.6.0 navigate:forward (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "php-cs-fixer",
      "atom-beautify"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
browser-plus, v0.0.24
linter, v1.2.3
linter-php, v0.0.15
linter-phpcs, v1.0.5
linter-phpmd, v0.0.11
navigate, v0.1.7
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Fixed..Check the latest version...Feel free to reopen..if it is still a problem
