### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sjwhyte** [skandasoft/navigate#12]
[Enter steps to reproduce below:]
1. I double click a function that  wanted to jump to and pushed (iOS) command - f2
2. error appeared

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.1.9
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/swhyte/.atom/packages/navigate/lib/navigate.coffee:51

TypeError: Cannot read property 'replace' of undefined
  at Object.module.exports.browserOption (/Users/swhyte/.atom/packages/navigate/lib/navigate.coffee:51:16)
  at Object.module.exports.openBrowser (/Users/swhyte/.atom/packages/navigate/lib/navigate.coffee:59:6)
  at atom-text-editor.atom.commands.add.navigate:browser (/Users/swhyte/.atom/packages/navigate/lib/navigate.coffee:40:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
 41x -4:47.3.0 bookmarks:jump-to-next-bookmark (atom-text-editor.editor.is-focused)
     -4:36.9.0 settings-view:open (atom-text-editor.editor.is-focused)
 11x -3:16.9.0 navigate:browser (atom-text-editor.editor.is-focused)
     -2:03.1.0 settings-view:open (a.btn-issue.btn.btn-error)
     -1:49.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:33.7.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  3x -1:21 navigate:browser (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "navigate": {
    "dblclk": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
atom-ctags, v4.1.4
browser-plus, v0.0.30
colorful-json, v1.0.0
go-plus, v3.4.3
javascript-snippets, v1.0.0
json-colorer, v0.3.0
json-schema, v0.1.10
jsonlint, v1.1.2
navigate, v0.1.9
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Can you check the latest. Also can you help me check cmd-f1,cmd-f2,cmd-f3 works in mac

**Comment by skandasoft** [comment]
assuming the issue is resolved...please feel free to reopen if it still a problem
