### ISSUE TITLE
Uncaught TypeError: atom.project.getPath is not a function

### ISSUE THREAD

**Issue by knai9** [skandasoft/navigate#16]
[Enter steps to reproduce below:]
1. ...navigate:refresh
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.1.10
### Stack Trace

Uncaught TypeError: atom.project.getPath is not a function

```
At /Users/ken/.atom/packages/navigate/lib/navigate.coffee:64

TypeError: atom.project.getPath is not a function
    at Object.module.exports.refresh (/Users/ken/.atom/packages/navigate/lib/navigate.coffee:64:32)
    at atom-text-editor.atom.commands.add.navigate:refresh (/Users/ken/.atom/packages/navigate/lib/navigate.coffee:32:66)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
```
### Commands

```
 51x -2:35.1.0 navigate:forward (atom-text-editor.editor.is-focused)
 20x -2:02.5.0 navigate:forward-new (atom-text-editor.editor.is-focused)
  5x -1:51.3.0 navigate:back (atom-text-editor.editor.is-focused)
  2x -0:14.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 navigate:refresh (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {},
  "navigate": {}
}
```
### Installed Packages

``` coffee
# User
browser-plus, v0.0.54
javascript-snippets, v1.0.0
navigate, v0.1.10

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
check the latest patch.

**Comment by skandasoft** [comment]
assumming the latest patch fixed the issue.
