### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by BlaM** [skandasoft/navigate#24]
[Enter steps to reproduce:]

1. Edit source code file (both JavaScript and PHP in my case)
2. Press F1 to open devdocs help
3. Explode

Not 100% sure, but may be related to update to Atom 1.19 this morning.

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package 0.1.17

### Stack Trace

Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

```
At C:\Users\ddeobald\.atom\packages\navigate\lib\navigate.coffee:53

TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.browserOption (/packages/navigate/lib/navigate.coffee:53:43)
    at Object.openBrowser (/packages/navigate/lib/navigate.coffee:68:6)
    at /packages/navigate/lib/navigate.coffee:42:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:01.7.0 intentions:highlight (input.hidden-input)
     -1:01.0 core:save (input.hidden-input)
     -0:51.2.0 core:move-left (input.hidden-input)
     -0:50.6.0 intentions:highlight (input.hidden-input)
     -0:50.5.0 core:paste (input.hidden-input)
     -0:50.2.0 intentions:highlight (input.hidden-input)
     -0:50.1.0 core:save (input.hidden-input)
     -0:48.3.0 intentions:highlight (input.hidden-input)
     -0:48.2.0 core:copy (input.hidden-input)
     -0:47.3.0 intentions:highlight (input.hidden-input)
     -0:47.3.0 core:paste (input.hidden-input)
     -0:47 intentions:highlight (input.hidden-input)
     -0:46.9.0 core:save (input.hidden-input)
     -0:30.3.0 intentions:highlight (input.hidden-input)
     -0:30.3.0 core:move-to-bottom (input.hidden-input)
     -0:08.8.0 navigate:browser (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
atom-jsx-transform 0.2.0 
atom-minify 0.8.0 
atom-pair 2.0.12 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
color-tabs 0.1.8 
color-tabs-regex 0.2.5 
colorful-json 1.1.0 
cson 2.0.1 
date 1.2.2 
devdocs 0.2.1 
documentation-renderer 0.2.1 
drunken-php 0.2.3 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
flex-tool-bar 0.12.0 
format-sql 0.3.0 
git-time-machine 1.5.9 
hg-commit 0.4.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
js-refactor 0.7.5 
json-colorer 1.0.0 
keyboard-localization 1.5.0 
language-apache 1.7.0 
language-babel 2.70.2 
language-docker 1.1.8 
language-erlang 3.2.0 
language-javascript-jsx 0.3.7 
language-log 1.8.0 
language-nginx 0.8.0 
language-sql-mysql 0.3.1 
language-vue 0.23.1 
less-autocompile 1.0.0 
linter 2.2.0 
linter-docker 0.2.0 
linter-erlc 0.3.1 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-jsonlint 1.3.0 
linter-package-json-validator 2.0.0 
linter-php 1.3.2 
linter-ui-default 1.6.4 
lodash-snippets 2.0.0 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
navigate 0.1.17 
node-debugger undefined 
open-recent 5.0.0 
package-sync-plus 0.1.2 
permanent-delete 0.1.5 
pigments 0.40.2 
prettier-atom 0.37.0 
pretty-json 1.6.4 
project-manager 3.3.5 
qolor 0.4.2 
react-snippets 0.9.0 
refactor 0.11.5 
regex-railroad-diagram 0.19.3 
Remote-FTP 1.1.3 
sass-autocompile 0.13.3 
select-rectangle 1.0.2 
selector-to-tag 0.4.2 
snippet-generator 0.3.2 
sort-lines 0.14.0 
split-diff 1.4.3 
sync-settings 0.8.2 
text-manipulation 0.6.0 
title-case 0.4.0 
tool-bar 1.1.0 
uglify 1.3.1 
uuidgen 1.2.1 
webbox-color 0.5.9 
```

**Comment by songkl** [comment]
navigate/lib/navigate.coffee   line:46   
```
key = evt.originalEvent.keyIdentifier || evt.originalEvent.key
```

**Comment by skandasoft** [comment]
taken care
