### ISSUE TITLE
don't open a modal window

### ISSUE THREAD

**Issue by despairblue** [skandasoft/navigate#5]
The modal window blocks the editor, which is not necessary if one double clicks only to select a whole word instead wanting to open another file.

**Comment by skandasoft** [comment]
Check the latest version. I have added a setting for double click(switched on by default). you can switch it off. so if you would like to navigate use 'f2' and 'f3' for back. 

And BTW does the modal window(with the github picture - loading gif) stay long enough to bother you/does it remain there without closing..for it is not even a second..so it doesn't bother me..i prefer double click and f3 back into the file..

**Comment by despairblue** [comment]
Ok, weird. Does it depend on the size of the project? Because in my case it
stays 2 to 3 seconds, the first time even longer. Also what theme are you
using? I noticed in another case that the modal window from the one theme
is actually a lot more intrusive than from other themes, since it overlays
a semi transparent veil on top of the whole editor.

**Comment by skandasoft** [comment]
check the latest version...

**Comment by despairblue** [comment]
![screenshot from 2015-05-04 00-21-02](https://cloud.githubusercontent.com/assets/927609/7447242/7f6e44d4-f1f3-11e4-9f39-0d86f1ea3977.png)

The error is: 
1. double clicked `container`

BTW: using command palette -> _Navigate: Forward_ works.

**Atom Version**: 0.196.0
**System**: linux 3.14.39-1-lts
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'container'

```
At module.js:330

Error: Cannot find module 'container'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at /home/despairblue/.atom/packages/navigate/lib/navigate.coffee:139:87
  at Object.module.exports.forward (/home/despairblue/.atom/packages/navigate/lib/navigate.coffee:145:7)
  at atom-text-editor.module.exports.activate.atom.workspace.observeTextEditors.view.ondblclick (/home/despairblue/.atom/packages/navigate/lib/navigate.coffee:37:12)

```

### Commands

```
     -0:22.1.0 pane:close (atom-text-editor.editor.is-focused)
     -0:21.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:18.9.0 core:backspace (atom-text-editor.editor.mini)
     -0:18.6.0 core:confirm (atom-text-editor.editor.mini)
     -0:16.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:16.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:13.2.0 core:confirm (atom-text-editor.editor.mini)
     -0:11.6.0 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "navigate": {
    "dblclick": true
  }
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.0
atom-color-highlight, v3.0.9
atom-ternjs, v0.5.23
atom-zeal, v0.1.0
autocomplete-css, v0.6.0
autocomplete-emojis, v2.2.0
autocomplete-html, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.7.0
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v1.0.0
file-icons, v1.5.4
git-log, v0.3.0
go-plus, v3.3.9
grammar-token-limit, v0.1.1
highlight-selected, v0.9.2
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-javascript-better, v1.5.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.11.0
language-tss, v0.1.0
latex, v0.22.0
linter, v0.12.1
linter-coffeelint, v0.2.2
linter-htmlhint, v0.0.13
linter-js-standard, v0.1.5
linter-js-yaml, v1.0.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.3
navigate, v0.1.0
open-last-project, v0.4.1
pdf-view, v0.22.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
I tried to put a try catch around that ..so that it doesn't through you out...Check the latest one.
